#!/bin/bash

echo "============================================"
echo "  Grafana Dashboard - Quick Test Summary"
echo "============================================"
echo ""
echo "📊 Dashboard: Observability Main"
echo "🔗 URL: http://localhost:3000/d/observability-main"
echo "👤 Credentials: admin / admin"
echo ""
echo "✅ Test Results: ALL PASSED (15/15)"
echo ""
echo "Tests Performed:"
echo "  ✓ Grafana health and authentication"
echo "  ✓ ClickHouse datasource connectivity"
echo "  ✓ Database and table structure"
echo "  ✓ Query execution (count, time series, distribution)"
echo "  ✓ Dashboard configuration and panels"
echo "  ✓ Auto-refresh settings"
echo ""
echo "📈 Current Data:"
echo "  • User Events: $(curl -s 'http://localhost:8123/?query=SELECT%20COUNT(*)%20FROM%20observability.user_events%20FORMAT%20TabSeparated')"
echo "  • Product Events: $(curl -s 'http://localhost:8123/?query=SELECT%20COUNT(*)%20FROM%20observability.product_events%20FORMAT%20TabSeparated')"
echo ""
echo "📋 Dashboard Features:"
echo "  • 10 visualization panels"
echo "  • Real-time monitoring"
echo "  • Auto-refresh every 10 seconds"
echo "  • Time series, pie charts, tables"
echo "  • 24-hour trend analysis"
echo ""
echo "🔧 Available Scripts:"
echo "  ./test-grafana-dashboard.sh     - Run full test suite"
echo "  ./generate-test-data.sh         - Generate sample data"
echo ""
echo "📖 Documentation:"
echo "  GRAFANA_DASHBOARD.md            - Dashboard guide"
echo "  GRAFANA_TEST_REPORT.md          - Detailed test report"
echo ""
echo "============================================"
